'use strict';

var Logger = require('dw/system/Logger').getLogger('BM-Extension');
var Resource = require('dw/web/Resource');

/**
 * @description Validate auth tocken
 * @param {Object} tokenObj - Retrieved  by Salesforce.
 * @returns {boolean} - Indicator of valid token
 */
function isValidAuth(tokenObj) {
    /**
     * @property {String} issued_at Describes the time of generating the token.
     * @property {String} access_token Represents the tokenValue generated by the source system.
     */
    return !(!tokenObj || !tokenObj.access_token || !tokenObj.issued_at);
}

/**
 * @description Returns whether the stored token expired or not
 * @param {Object} tokenObj - The token object retrieved from the auth API response
 * @returns {boolean} - Whether the token is valid
 */
function isAuthTokenExpired(tokenObj) {
    return Boolean(
		!tokenObj ||
        (tokenObj.access_token && tokenObj.expires_at && (Date.now() >= tokenObj.expires_at))
	);
}

/**
 * @description Retrieves a valid OCI auth token from storage or from a new auth request
 * @param {boolean} bypassCache - If true, then the token will not be retrieved from the cache
 * @returns {Object} - Plain JS object containing the token response
 */
function readAuthToken(bypassCache) {
    var CacheMgr = require('dw/system/CacheMgr');
    var CACHE_KEY = 'ociCommerceApiAuthToken';
    var cache = CacheMgr.getCache(CACHE_KEY);
    var ociServiceAuth;

    if (bypassCache) {
        cache.invalidate(CACHE_KEY);
    }

    var tokenObj = cache.get(CACHE_KEY, function requestAuthToken() {
        var ociAuthService = require('~/cartridge/scripts/services/oci/auth');
        var result = ociAuthService.call();
        var accessTokenData = result.object;
        if (!empty(accessTokenData)) {
            ociServiceAuth = accessTokenData;
            accessTokenData = accessTokenData.tokenObj;
        } else {
            ociServiceAuth = {
                error: true,
                serviceError: true,
                errorMessage: result.errorMessage
            };
        }

        return accessTokenData;
    });

    if (!isValidAuth(tokenObj)) {
        ociServiceAuth = {
            error: true,
            expired: true,
            errorMessage: Resource.msg('error.oci.token.missing', 'common', null)
        };
    }

    if (!ociServiceAuth) {
        ociServiceAuth = {
            error: false,
            tokenObj: tokenObj
        };
    }

    return ociServiceAuth;
}

/**
 * @description Gets a valid token from storage or from a new auth request
 * @returns {Object} - Plain JS object containing the token response
 */
function getAuthToken() {
    var token = readAuthToken(false);

    if (token.error || isAuthTokenExpired(token.tokenObj)) {
        token = readAuthToken(true);
    }

    return token;
}

/**
 * Call OCI
 * @param {Object} ociReq - OCI request.
 * @returns {Object} ociServiceResult
 */
function callOciService(ociReq) {
    var ociService = require('~/cartridge/scripts/services/oci/rest');
    var OCIResponse = require('~/cartridge/scripts/util/ociUtils/ociResponse');
    var Result = require('dw/svc/Result');
    var authToken = getAuthToken();
    var ociServiceResult;

    if (!authToken.error && authToken.tokenObj) {
        var args = {
            ociEndpointUrl: ociReq.ociEndpointUrl,
            requestMethod: ociReq.httpMethod,
            headers: ociReq.headers,
            request: ociReq.body,
            accessToken: authToken.tokenObj.access_token
        };
        var result = ociService.call(args);
        if (result && result.ok) {
            var resultObj = {
                data: result.object
            };
            ociServiceResult = resultObj;
        } else if (result && result.status !== Result.SERVICE_UNAVAILABLE && result.errorMessage.indexOf('java.net.SocketException') === -1) {
            var errorMessage;
            try {
                errorMessage = JSON.parse(result.errorMessage);
            } catch (e) {
                Logger.error('Error while parsing oci error message: {0}#{1}\n{2}\n{3}', e.fileName, e.lineNumber, e.message, e.stack);
            }
            var ociRes = new OCIResponse(errorMessage, result.error.toString());
            ociServiceResult = ociRes.getObject();
        } else if (result.unavailableReason === Result.UNAVAILABLE_TIMEOUT) {
            ociServiceResult = {
                error: true,
                serviceError: true,
                data: { errorMessage: Resource.msg('error.oci.time.out', 'common', null) }
            };
        } else {
            ociServiceResult = {
                error: true,
                serviceError: true,
                data: { errorMessage: result.errorMessage }
            };
        }
    } else {
        ociServiceResult = {
            error: true,
            serviceError: true,
            data: { errorMessage: authToken.errorMessage }
        };
    }
    return ociServiceResult;
}

module.exports = {
    callOciService: callOciService
};
