'use strict';

module.exports = {
    'oos.email.subject': 'Alert: {0} - Product Out-of-Stock Notification',
    'oos.email.message.header': '<p>Dear Admin,</p><p>We wanted to inform you that the product(s) mentioned below (be) now sold out and marked as "Out-of-Stock" in <b>{0}</b>. This may affect your ongoing orders or planned purchases. </p>',
    'oos.email.message.footer': '<p>Thank you for your attention to this matter. </p><p>Best regards, <br>Business Manager Extension </p>',
    'oos.email.column1': 'Product ID',
    'order.alert.subject': 'Alert: {0} - No Orders Notification',
    'order.alert.message.header': '<p>Dear Admin,</p><p>We wanted to bring to your attention that there have been no orders placed in <b>{0}</b> within the specified timeframe ({1}). This may indicate a potential issue with the ordering process or a temporary lull in customer activity.</p>',
    'order.alert.message.footer': '<p>Thank you for your attention to this matter.</p><p>Best regards,<br>Business Manager Extension</p>',
    'failedorder.email.subject': 'Alert: {0} - Failed Orders Notification',
    'failedorder.email.message.header': '<p>Dear Admin,</p><p>We wanted to inform you that we&#39;ve observed a higher-than-usual number of failed orders in <b>{0}</b> recently. This may require your attention to investigate any potential issues with the ordering process.</p>',
    'failedorder.email.message.footer': '<p>Thank you for your prompt attention to this matter.</p><p>Best regards,<br>Business Manager Extension</p>',
    'failedorder.email.column1': 'Order No',
    'failedorder.email.column2': 'Creation Date',
    'campaign.message': 'The system will send notifications to the recipient email addresses if any of the specified campaigns needs a specific time to end which is equal or lower than the value set in the time interval field.',
    'campaign.email.subject': 'Alert: {0} - Marketing Campaign Expiration Notification',
    'campaign.email.message.header': '<p>Dear Admin,</p><p>We wanted to notify you that the following marketing campaign(s) in <b>{0}</b> (be) nearing expiration within the specified timeframe:</p>',
    'campaign.email.message.footer': '<p>Please review (this/these) campaign(s) and take any necessary actions to ensure a smooth transition or extension if needed.</p><p>Thank you for your attention to this matter.</p><p>Best regards,<br>Business Manager Extension</p>',
    'campaign.email.column1': 'Campaign ID',
    'campaign.email.column2': 'End Date',
    'campaign.email.expiredat': 'Expired at ',
    'content.invalid.value': 'page ID: {0} is invalid page ID in the current site',
    'invalid.content.for.site': 'The entered page IDs have invalid value(s) for the current site',
    'no.pages.in.site': 'The current site has no page designer pages',
    'proccess.xml.error': 'error while processing library xml file: {0}',
    'order.alert.interval.days': '{0} day(s)',
    'order.alert.interval.hours': '{0} hour(s)',
    'order.alert.interval.minutes': '{0} minute(s)',
    'common.and': ' and '
};
